Updated website release note 0.35.0
eclipse-openj9/openj9-website pull request #324
Opened 2022-10-19 11:33 UTC by Sreekala-Gopakumar

https://github.com/eclipse-openj9/openj9-website/issues/320

Updated the website release notes for 0.35.0

Signed-off-by: Sreekala Gopakumar <sreekala.gopakumar@ibm.com>

2022-10-19 11:34 UTC, Sreekala-Gopakumar commented
Jenkins website stage

2022-10-19 11:43 UTC, Sreekala-Gopakumar commented
@pshipton @doveye @mpirvu @keithc-ca @yathamravali @dsouzai @kgibm @vijaysun-omr - Updated the document as per the draft created in https://github.com/eclipse-openj9/openj9-website/issues/320. Please let me if anything else has to be added or deleted. Thanks!

2022-10-19 12:47 UTC, mpirvu reviewed
LGTM

2022-10-19 20:10 UTC, keithc-ca commented on news-page-content/latestRelease.md
> +- `-XX:+EnsureHashed:java/lang/Class,java/lang/Thread` is added to the list of default options in the `options.default` file for pre-hashing those objects from the start and hence, improve the perfor
I think "improve" should be "improving" here:

> hashing those objects from the start and hence, improving performance

2022-10-19 20:10 UTC, keithc-ca commented on news-page-content/latestRelease.md
Please also delete this line: we don't need two blank lines at the end of the file.

2022-10-20 06:33 UTC, Sreekala-Gopakumar commented on news-page-content/latestRelease.md
> +- `-XX:+EnsureHashed:java/lang/Class,java/lang/Thread` is added to the list of default options in the `options.default` file for pre-hashing those objects from the start and hence, improve the perfor
Done with an additional change.

2022-10-20 06:33 UTC, Sreekala-Gopakumar commented on news-page-content/latestRelease.md
Done.

2022-10-20 14:38 UTC, keithc-ca commented on news-page-content/latestRelease.md
> +- `-XX:+EnsureHashed:java/lang/Class,java/lang/Thread` is added to the list of default options in the `options.default` file for pre-hashing the `Class` and `Thread` class objects from the start and
I would also change "the performance" to just "performance".

2022-10-20 14:41 UTC, keithc-ca commented on news-page-content/latestRelease.md
> +- `-XX:[+|-]JITServerLocalSyncCompiles` enabled by default in most cases for improving the latency of the compilations that are performed synchronously
My earlier suggestion was to make the phrase self-consistent; I'm happy with the change for  `EnsureHashed`, but, as I said, I think the text for `JITServerLocalSyncCompiles` was better before. I don't understand the qualification "in most cases". I would write 

> JITServerLocalSyncCompiles is enabled by default to reduce the latency of the compilations that are performed synchronously

2022-10-20 14:45 UTC, mpirvu commented on news-page-content/latestRelease.md
> +- `-XX:[+|-]JITServerLocalSyncCompiles` enabled by default in most cases for improving the latency of the compilations that are performed synchronously
`JITServerLocalSyncCompiles` is not always enabled by default. If the user decides to disable recompilation or to disable asynchronous compilation or use the JVM in debug mode, then this feature is disabled.

2022-10-20 14:48 UTC, keithc-ca commented on news-page-content/latestRelease.md
> +- `-XX:[+|-]JITServerLocalSyncCompiles` enabled by default in most cases for improving the latency of the compilations that are performed synchronously
Then is should not use the phrase "by default", it should say "is enabled in most cases", perhaps with a link that provides more detail about those "cases".

2022-10-21 10:46 UTC, Sreekala-Gopakumar commented
Jenkins website stage

2022-10-21 11:40 UTC, pshipton requested changes
Merging this is pending until the 0.35 release is ready to GA.

2022-10-21 17:45 UTC, keithc-ca approved these changes

2022-10-25 18:38 UTC, pshipton commented
The current target to complete testing for AArch64 Mac is Nov 15. We may need to remove the line `Apple silicon macOS&reg; is now a fully supported, production-ready target for OpenJDK 11 and later.` if the 0.35 release is published before then, which it likely will be.

2022-10-28 17:45 UTC, pshipton approved these changes

2022-10-28 17:55 UTC, keithc-ca approved these changes

2022-10-28 17:55 UTC, merged